### ISSUE TITLE
TFMongoDB support for Linux (Ubuntu)

### ISSUE THREAD

**Issue by sindbach** [svenboesiger/tfmongodb#2]
Hi @svenboesiger 
What's currently preventing TFMongoDB support for Linux ? Is there a specific problem that I may be able to help with ? 

I could get TFMongoDB to work with Tensorflow v1.11 by compiling MongoDB C/C++ driver with no CXX11 in Ubuntu 18.04. 

Regards,

**Comment by svenboesiger** [comment]
Hi @sindbach 

You are right, there is actually nothing preventing TFMongoDB from working on Linux - in fact I am using it as well under Linux these days.

I solely introduced the limitated due to problems from my side to wrap the driver in a proper pip package compatible with Mac OS X and Linux at the same time (Mostly a time issue).

**Comment by sindbach** [comment]
Good to know, Thanks!

**Comment by mahmoudakl** [comment]
Hey @svenboesiger ,
Can you tell me how your setup on Linux looks like, I'm running into a bunch of errors.
First I tried running with tensorflow 1.13 and I got the following error:
`TypeError: Can't instantiate abstract class MongoDBDataset with abstract methods _inputs`
And then I tried upgrading tensorflow but I got the following error:
`File "tfmongodb.py", line 24, in <module>
    from tensorflow.data import Dataset
ImportError: No module named data
`
Any help is much appreciated.

Thanks,

**Comment by sindbach** [comment]
@mahmoudakl 
The current master branch only supports up to TensorFlow 1.11. 
Also MongoDB C driver v1.13.0 and C++ driver v3.3.1

Cheers.
